### ISSUE TITLE
Rails 5.0 Support

### ISSUE THREAD

**Issue by aahmad** [HornsAndHooves/pg_saurus#33]
We are migrating from a previous version of Rails to Rails 5.0.7, and bumping the `pg_saurus` gem up causes this error:

```
Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (= 5.0.7)

  In Gemfile:
    pg_saurus was resolved to 4.0.2, which depends on
      railties (~> 5.2.3)
```

Is there any way around it; I do see the gemspec locking it to `~> 5.2.3`

Thank you

**Comment by albertosaurus** [comment]
The problem is that we currently don't have the manpower to target multiple Rails minor versions. I'll do a sanity check and see if it even works on 5.0. I think the best case we'll be able to do (assuming no issues on 5.0) is relax the version requirements to 5.X and explicitly warn that anything under 5.2 isn't officially targeted.

**Comment by aahmad** [comment]
That is okay; understandably, there is limited manpower. I will simply upgrade the Rails app to 5.1, then 5.2, and plug the gem back in. Thank you!

**Comment by aahmad** [comment]
I've upgraded all to Rails `5.2.4`, however when running `bundle exec rails c`, I get the following error:

```
bundler: failed to load command: rails (/Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/rails)
LoadError: cannot load such file -- /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/pg_saurus-32a30e23479f/test/dummy/config/application
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/actions.rb:22:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/actions.rb:22:in `require_application!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/commands/console/console_command.rb:95:in `perform'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/base.rb:69:in `perform'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command.rb:46:in `invoke'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine/commands.rb:9:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine/commands.rb:9:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/pg_saurus-32a30e23479f/bin/rails:14:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/pg_saurus-32a30e23479f/bin/rails:14:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/rails:23:in `load'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/rails:23:in `<top (required)>'
```

Interestingly, `./bin/rails console` works - any clue as to what's wrong?

The `Gemfile` shows this:

```
gem "pg_saurus", git: "https://github.com/HornsAndHooves/pg_saurus"
```

Thank you!

**Comment by albertosaurus** [comment]
Should work now. I've fixed the "bin/rails" shortcut. Should have been `File.expand_path('../spec/dummy/config/application', __dir__)` instead of `File.expand_path('../test/dummy/config/application', __dir__)`.

**Comment by aahmad** [comment]
Thank you so much for the fast response. I tried that locally before messaging but received this - the stack trace looks different than before:

```
bundler: failed to load command: rails (/Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/rails)
Doorkeeper::MissingConfiguration: Configuration for doorkeeper missing. Do you have doorkeeper initializer?
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/doorkeeper-5.0.0/lib/doorkeeper/config.rb:18:in `configuration'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/doorkeeper-5.0.0/app/controllers/doorkeeper/application_controller.rb:3:in `<module:Doorkeeper>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/doorkeeper-5.0.0/app/controllers/doorkeeper/application_controller.rb:1:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:476:in `load'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:476:in `block in load_file'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:475:in `load_file'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:373:in `block in require_or_load'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:37:in `load_interlock'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:356:in `require_or_load'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:334:in `depend_on'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:246:in `require_dependency'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine.rb:477:in `each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine.rb:477:in `block in eager_load!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine.rb:475:in `each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine.rb:475:in `eager_load!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine.rb:356:in `eager_load!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/application/finisher.rb:69:in `each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/initializable.rb:32:in `instance_exec'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/initializable.rb:32:in `run'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/initializable.rb:61:in `block in run_initializers'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/initializable.rb:60:in `run_initializers'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/application.rb:361:in `initialize!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/railtie.rb:190:in `public_send'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/railtie.rb:190:in `method_missing'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/pg_saurus-5d734f66bba6/spec/dummy/config/environment.rb:5:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/application.rb:337:in `require_environment!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/actions.rb:28:in `require_environment!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/commands/console/console_command.rb:95:in `perform'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command/base.rb:69:in `perform'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/command.rb:46:in `invoke'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine/commands.rb:9:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-5.2.4/lib/rails/engine/commands.rb:9:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/pg_saurus-5d734f66bba6/bin/rails:14:in `require'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/pg_saurus-5d734f66bba6/bin/rails:14:in `<top (required)>'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/rails:23:in `load'
  /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/rails:23:in `<top (required)>'
```

It seems to be some odd loading order. In my `config/environments/development.rb`, I have `  config.eager_load = false`. 

`bin/rails s` works and the contents are:

```
#!/usr/bin/env ruby
APP_PATH = File.expand_path('../config/application', __dir__)
require_relative '../config/boot'
require 'rails/commands'
```

Thank you ever so much!

**Comment by seifertd** [comment]
Is there something wrong with the published Gem? I see neither a spec nor a test directory at the top level of the library after it is installed:

`
ls /Users/ME/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/pg_saurus-4.0.2/
README.markdown bin             lib
`
As a work around, @aahmad's advice works, but the code in /Users/ME/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/pg_saurus-4.0.2/bin/rails is doomed to not ever run if the file #{__dir__}/../test/dummy/config/application does not exist.

**Comment by seifertd** [comment]
On second thought: why does pg_saurus even try to export a bin/rails executable? I was able to avoid the issue described here by moving the declaration of the pg_saurus dependency to the top of my Rails app's Gemfile. Then the bin/rails exported by the railties gem overwrites the one exported by pg_saurus. 

I suspect the solution here will be to modify the pg_saurus gemspec file to delete this line: https://github.com/HornsAndHooves/pg_saurus/blob/master/pg_saurus.gemspec#L17

**Comment by albertosaurus** [comment]
@seifertd Leftover cruft from internal usage years ago. FWIW, we've been planning to move away from Jeweler for a while, but can't quite find the time.
